//@ui5-bundle gitpg/myapp/Component-preload.js
sap.ui.require.preload({
	"gitpg/myapp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","gitpg/myapp/model/models"],function(e,t,i){"use strict";return e.extend("gitpg.myapp.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"gitpg/myapp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("gitpg.myapp.controller.controller.App",{onInit(){}})});
},
	"gitpg/myapp/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","gitpg/myapp/model/formatter"],function(e,t,o,n){"use strict";return e.extend("gitpg.myapp.controller.BaseController",{formatter:n,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){const e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"gitpg/myapp/controller/MainView.controller.js":function(){sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("gitpg.myapp.controller.MainView",{onInit:function(){let e=new t;this.getView().setModel(e,"myNode");e.loadData("https://port-8921-nodejs-quaint-lizard-lgx0920328747.codeanyapp.com/files").then(function(){debugger}.bind(this))}})});
},
	"gitpg/myapp/i18n/i18n.properties":'# This is the resource bundle for gitpg.myapp\r\n\r\n#Texts for manifest.json\r\n\r\n#XTIT: Application name\r\nappTitle=Title of gitpg.myapp\r\n\r\n#YDES: Application description\r\nappDescription=Description of gitpg.myapp\r\n#XTIT: Main view title\r\ntitle=Title of gitpg.myapp',
	"gitpg/myapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"gitpg.myapp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap-ux/fiori-freestyle-writer:basic","version":"0.11.15"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"gitpg.myapp.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"gitpg.myapp.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMainView","pattern":":?query:","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"MainView","viewName":"MainView"}}},"rootView":{"viewName":"gitpg.myapp.view.App","type":"XML","async":true,"id":"App"}}}',
	"gitpg/myapp/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"gitpg/myapp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){const i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"gitpg/myapp/view/App.view.xml":'<mvc:View controllerName="gitpg.myapp.controller.App" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><App id="app"></App></mvc:View>\r\n',
	"gitpg/myapp/view/MainView.view.xml":'<mvc:View controllerName="gitpg.myapp.controller.MainView" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m" xmlns:tnt="sap.tnt"><Page id="page" title="{i18n>title}"><content><tnt:NavigationList id="navigationList" width="320px" selectedKey="Files"><tnt:items><tnt:NavigationListItem id="myListItemHeader" text="myFiles" key="rootItem1" icon="sap-icon://document" items="{myNode>/}"><tnt:items><tnt:NavigationListItem id="myListItem" text="{myNode>}" /></tnt:items></tnt:NavigationListItem></tnt:items></tnt:NavigationList></content></Page></mvc:View>'
});
